// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int nTimes = Integer.parseInt(args[0]);
		int i = 0;
		int big = 0;
		int small = 0;
		
		while (i < nTimes ) {double random = Math.random();
			if (random >= 0.5){big++;}if (random < 0.5) {
			small++;}
			i++;
			
		}
			System.out.println("> 0.5:" + " " + (int)big + " Times");
			System.out.println("<= 0.5:" + " " + (int)small + " Times");
			System.out.println("Ratio:" + " " + (double)big/(double)small);

		


	}
}
